### ISSUE TITLE
Swear Censoring

### ISSUE THREAD

**Issue by dankstache** [mmguero/cleanvid#28]
Hey, I'm rather new to python and coding in general but quick learned. I've been at it for hours trying to get this script to work and for the life of me cannot.

PS C:\Users\Kaize> cleanvid -i "C:\Users\Kaize\OneDrive\Pictures\Camera Roll\WIN_20240205_12_48_28_Pro.mp4" -w "D:\Programs\Python 3\Lib\site-packages\cleanvid\swears.txt" -o "C:\Users\Kaize\OneDrive\Pictures\Camera Roll\Censored"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Programs\Python 3\Scripts\cleanvid.exe\__main__.py", line 7, in <module>
  File "D:\Programs\Python 3\Lib\site-packages\cleanvid\cleanvid.py", line 663, in RunCleanvid
    subsFile = GetSubtitles(inFile, lang, args.offline)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python 3\Lib\site-packages\cleanvid\cleanvid.py", line 147, in GetSubtitles
    savedSub = save_subtitles(video, [bestSubtitles[video][0]])
                                      ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

This is what I'm getting. I'm not worried about subtitles I just need the profanity in videos muted. I've tried --offline as well and still nothing. I'm using windows powershell.

**Comment by mmguero** [comment]
When you say "I'm not worried about subtitles," you're misunderstanding how this project works. Cleanvid knows where to mute the profanity *because of* the subtitles. It's not doing speech recognition, it's just reading the subtitle files and using that to base the muting off of.

The error (list index out of range) is saying "I couldn't find the subtitles for this movie." If it's a video file without subtitles, you aren't going to get anything from it.

However, I do have a program called [monkeyplug](https://github.com/mmguero/monkeyplug) which does speech recognition. It was originally intended for audio files only, but as my readme says:
> If provided a video file for input, monkeyplug will attempt to process the audio stream from the file and remultiplex it, copying the original video stream.

So you could try that. Monkeyplug works best on clearly spoken audio. There are some plans to improve its capabilities by switching from vosk to whisper, when I get time.
